/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import {HTMLStencilElement, JSXBase} from '@stencil/core/internal';
export namespace Components {
  interface OwllySign {
    /**
     * An aria-label for the shadowed button. Per default "sign" translated in de, fr, it or en according browser lang.
     */
    ariaLabel: string;
    /**
     * IntersectionObserver rootMargin property.
     */
    observerRootMargin: string;
    /**
     * IntersectionObserver threshold property.
     */
    observerThreshold: number | number[];
  }
}
declare global {
  interface HTMLOwllySignElement extends Components.OwllySign, HTMLStencilElement {}
  var HTMLOwllySignElement: {
    prototype: HTMLOwllySignElement;
    new (): HTMLOwllySignElement;
  };
  interface HTMLElementTagNameMap {
    'owlly-sign': HTMLOwllySignElement;
  }
}
declare namespace LocalJSX {
  interface OwllySign {
    /**
     * An aria-label for the shadowed button. Per default "sign" translated in de, fr, it or en according browser lang.
     */
    ariaLabel?: string;
    /**
     * IntersectionObserver rootMargin property.
     */
    observerRootMargin?: string;
    /**
     * IntersectionObserver threshold property.
     */
    observerThreshold?: number | number[];
  }
  interface IntrinsicElements {
    'owlly-sign': OwllySign;
  }
}
export {LocalJSX as JSX};
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'owlly-sign': LocalJSX.OwllySign & JSXBase.HTMLAttributes<HTMLOwllySignElement>;
    }
  }
}
